apiVersion: v1
kind: Service
metadata:
  #Srvrice make the application network available form targetPort to nodePort
  name: cmpsite-service
  namespace: cmpsite-namespace
  labels:
    app: cmpsite
spec:
  type: NodePort
  ports:
  - port: 8000
    protocol: TCP
    #Port listening by the cmpsite application inside the container
    targetPort: 8000
    #Public acessible port
    nodePort: 30008
  selector:
    app: cmpsite
